#!/usr/bin/env python
from stdr_dead_reckoning.talker_module import Talker
if __name__ =='__main__':
    # Create an instance of the Talker class
    talker_instance = Talker()
    talker_instance.talker()